version: "3"

services:
  web:
    image: bill00lee/services:0.1
    deploy:
      replicas: 7
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8750:8100"
    networks:
      - webnet

networks:

  webnet:

